mywordpress:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: wordpress
  links:
  - database:mysql
  stdin_open: true
mywordpresslb:
  ports:
  - 8090:80
  tty: true
  image: rancher/load-balancer-service
  links:
  - mywordpress:mywordpress
  stdin_open: true
database:
  environment:
    MYSQL_ROOT_PASSWORD: pass1
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: mysql
  stdin_open: true
